name: ESLint
on:
  pull_request:
    branches: [main]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enable corepack
        run: corepack enable
      - name: Install modules
        run: yarn install --immutable
        env:
          YARN_ENABLE_SCRIPTS: false
      - name: Run ESLint
        run: yarn check-style
